### ISSUE TITLE
Crash when running benchmarks on my machine

### ISSUE THREAD

**Issue by Charanor** [Doraku/Ecs.CSharp.Benchmark#39]
Hello! I'm developing an ECS and wanted to use this to check its performance, however when running the benchmarks on my machine (Windows 10, running as administrator, on `master` branch **without any changes**) the script crashes when running the `SystemWithOneComponent.DefaultEcs_ComponentSystem_MonoThread` job. All benchmarks up until that point run fine.

Log file is attached, it does not include the exception so I will paste it below. The exception occurs between `// Benchmark Process 16068 has exited with code 0.` and `Successfully reverted power plan (GUID: 381b4222-f694-41f0-9685-ff5bb260df2e FriendlyName: Balanced)` lines at the very end of the log, if it matters.

[BenchmarkRun-20240607-055225.log](https://github.com/user-attachments/files/15707621/BenchmarkRun-20240607-055225.log)

```
Unhandled exception. System.InvalidOperationException: One workload iteration stop event is missing, unable to calculate stats
   at BenchmarkDotNet.Diagnostics.Windows.Tracing.ProcessMetrics.CalculateMetrics(Dictionary`2 profileSourceIdToInterval, PreciseMachineCounter[] counters)
   at BenchmarkDotNet.Diagnostics.Windows.Tracing.TraceLogParser.Parse(TraceLogEventSource traceLogEventSource, PreciseMachineCounter[] counters)
   at BenchmarkDotNet.Diagnostics.Windows.Tracing.TraceLogParser.Parse(String etlFilePath, PreciseMachineCounter[] counters)
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.ProcessResults(DiagnoserResults results)
   at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.<>c__DisplayClass10_0.<ProcessResults>b__0(IDiagnoser diagnoser)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, EventProcessor eventProcessor, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, Int32 totalBenchmarkCount, StartedClock& runsChronometer, Int32& benchmarksToRunCount, TaskbarProgress taskbarProgress)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at Program.<Main>$(String[] args) in E:\Projects\C#\Ecs.CSharp.Benchmark\source\Ecs.CSharp.Benchmark\Program.cs:line 32
```

P.S. is the benchmark supposed to take hours to run? The estimate (before crash) said something like 2h 50m which seems really long! Running on a i6 9600k @ 4.9Ghz with "high" priority in task manager for reference.

**Comment by Charanor** [comment]
Tried again, now I got further but got another error. I also noticed that the time estimate is crazy as you can see in attached log (almost 3h!), and the "ETL" files being generated are tens of gigabytes large! Is that intentional? After running only this many benchmarks (like seven) it has produced almost 50gb of these ETL files.

[BenchmarkRun-20240607-061638.log](https://github.com/user-attachments/files/15710610/BenchmarkRun-20240607-061638.log)


```
System.Exception: Merge operation failed return code 0x1069
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.Merge(String[] inputETLFileNames, String outputETLFileName, EVENT_TRACE_MERGE_EXTENDED_DATA flags)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.Merge(String[] inputETLFileNames, String outputETLFileName, TraceEventMergeOptions options)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.MergeInPlace(String etlFileName, TextWriter log)
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Stop(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Int32 launchIndex)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, EventProcessor eventProcessor, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, Int32 totalBenchmarkCount, StartedClock& runsChronometer, Int32& benchmarksToRunCount, TaskbarProgress taskbarProgress)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at Program.<Main>$(String[] args) in E:\Projects\C#\Ecs.CSharp.Benchmark\source\Ecs.CSharp.Benchmark\Program.cs:line 32
```
